### ISSUE TITLE
Feature Request - Open Link in New Window

### ISSUE THREAD

**Issue by awarner20** [WebDevStudios/EDD-External-Products#2]
Hi guys and gals, great Addon and just started testing it. Wonder if you'd consider an "Open in New Window" checkbox for the external links?

**Comment by awarner20** [comment]
Are there plans to update this and merge the "Open in New Window" additions @leewillis77 has made?

**Comment by williamsba** [comment]
Thanks for the nude Adam! :)

**Comment by awarner20** [comment]
Thanks for the fast response Brad, it's just what we needed at Foo for one of our offsite plugins.

p.s. I see you corrected the typo because I don't remember sending you any Nudes;)

**Comment by williamsba** [comment]
lol I was hoping my edit was made before the email went out hahaha

**Comment by awarner20** [comment]
Sorry to keep this going, but just updated and was (maybe falsely) expecting a checkbox for "Open in New Window". 

Regardless, I have it active on this product but still opens in same window?
http://fooplugins.com/plugins/foobar-pro-wp/

**Comment by williamsba** [comment]
This change just adds a filter to the link.  There were code examples provided on how to add target="_blank" to your URLs https://github.com/WebDevStudios/EDD-External-Products/pull/3

**Comment by awarner20** [comment]
Ah, ok...I'll dig in then. Thanks for clearing me up:)
