### ISSUE TITLE
Force link to open in _blank

### ISSUE THREAD

**Issue by halleg** [WebDevStudios/EDD-External-Products#8]
Hello,

Great and simple plugin. Can you advise how to force it to open new link in blank?

**Comment by Mamaduka** [comment]
You can use `edd_external_product_link_attrs` filter, example:

```
add_filter( 'edd_external_product_link_attrs', function( $atts ) {
    return 'target="_blank"';
});

**Comment by tw2113** [comment]
Closing as there is a filter for it.
